version: '3'

services:
  postgresdb:
    image: postgres:10.10
    environment:
      - POSTGRES_USER=angular_on_rails
      - POSTGRES_PASSWORD=angular_on_rails
      - POSTGRES_DB=angular_on_rails_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local